build: create docker file
joshiayush/inb pull request #55
Opened 2023-03-26 14:25 UTC by ologbonowiwi

This aims to solve #53.

2023-03-26 15:17 UTC, joshiayush requested changes

2023-03-26 15:17 UTC, joshiayush commented on Dockerfile
> +RUN pip install -r requirements.txt
Can you change this to `pip install --no-cache-dir -r requirements.txt`

2023-03-26 15:17 UTC, joshiayush commented on Dockerfile
> +
It would be good if you can remove this empty line here.

2023-03-26 15:17 UTC, joshiayush commented on Dockerfile
> +COPY . .
I don't think that we need to copy everything to the `/app` directory just copy the `inb` directory that's in the project's root directory. Change this directive to:

```Dockerfile
COPY inb /app
```

2023-03-26 15:17 UTC, joshiayush commented on Dockerfile
> +CMD [ "python", "app.py" ]
See the entry file is located inside of the `inb` directory which is [this](https://github.com/joshiayush/inb/blob/main/inb/inb.py). So please change this directive to:

```Dockerfile
CMD ["python", "inb/inb.py"]
```

2023-03-26 15:17 UTC, joshiayush commented on Dockerfile
> +CMD [ "python", "app.py" ]
And please add a newline character at the end of this file :+1:

2023-03-26 15:18 UTC, joshiayush commented
@ologbonowiwi Can you also update the `README` to include the guide on build and usage of the docker setup?

2023-03-26 16:20 UTC, ologbonowiwi commented
All comments addressed.

2023-03-26 16:28 UTC, merged

2023-03-26 16:33 UTC, joshiayush commented
Thanks @ologbonowiwi :+1: I'll be waiting for more contributions from your side

2023-03-27 03:52 UTC, joshiayush commented on README.md
> +## Docker usage
I didn't notice but I think we don't need the term "Docker usage" here, just "Docker" would be fine enough :+1: