fix/#62/fallback empty values to show on console
joshiayush/inb pull request #63
Opened 2023-05-06 04:13 UTC by ologbonowiwi

- test: add test with None values on invitation
- feat: print empty line when the value is None

2023-05-06 15:54 UTC, joshiayush requested changes
I really appreciate the fact that you consider adding tests for your changes. Keep it up and thanks for helping in my projects.

2023-05-06 15:54 UTC, joshiayush commented on inb/api/invitation/status.py
> +        # provide an empty string as the valid value
If `None` value is creating a problem then in that case these inline comments are not needed. The code itself is readily understandable, could you please remove them before I merge?

2023-05-06 15:54 UTC, joshiayush commented on inb/tests/test_invitation_status.py
> +                      '  \n'
There's a problem in indentation here and in the following lines, could you please fix that?

2023-05-06 15:54 UTC, joshiayush commented on inb/api/invitation/status.py
> +            replace_template_var_with_value_pair[0], '')
Moreover, this entire `if` `else` ladder could be made more readable if you could just change the above code to:

```python
template_var = replace_template_var_with_value_pair[0]
template_val = replace_template_var_with_value_pair[1]

if template_val is None:
  ...
else
  ... 
```

Could you please make this change before I merge?

2023-05-06 15:59 UTC, joshiayush requested changes

2023-05-06 15:59 UTC, joshiayush commented on inb/api/invitation/status.py
> +            replace_template_var_with_value_pair[0], '')
I would like to request one more change. Is there something else that we can display on console rather than empty values. Like some form of text or one word like `NaN` for better understanding? which will just tell the user that we couldn't find this one from the profile.

2023-05-07 03:29 UTC, ologbonowiwi commented on inb/api/invitation/status.py
> +            replace_template_var_with_value_pair[0], '')
If you have something in mind I'll be happy to implement it

2023-05-07 15:30 UTC, joshiayush commented on inb/api/invitation/status.py
> +            replace_template_var_with_value_pair[0], '')
Use `NaN` for now

2023-05-08 23:28 UTC, merged